<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> Homework 07. Ansible cruise Uladzimir Schuka
---
- hosts: webservers
  become: yes
  roles:
    - nginx
<<<<<<< HEAD
=======
---
- hosts: all
  become: true
  roles:
    - nginx
>>>>>>> Homework 07.Ansible.Cruise and 10.Jenkins.Start
=======
>>>>>>> Homework 07. Ansible cruise Uladzimir Schuka
