<<<<<<< HEAD
- name: Centos update repo
  yum:
    name: yum-utils
    update_cache: yes
    state: present

- name: Add nginx repo
  yum_repository:
    name: nginx-stable
    description: nginx stable repo
    baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
    gpgcheck: yes
    enabled: yes
    gpgkey: https://nginx.org/keys/nginx_signing.key

- name: Install nginx
  yum:
    name: nginx
    update_cache: yes
    state: present
=======
---
 - name: Add Repository
   yum:
     name: epel-release
     state: present

 - name: Install nginx
   package:
     name: nginx
     state: latest

 - name: Start nginx
   service:
     name: nginx
     state: started
     enabled: yes
>>>>>>> Homework 07.Ansible.Cruise and 10.Jenkins.Start
